### ISSUE TITLE
Activate dependabot to keep Rust dependencies and GitHub Actions up-to-date

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pn#31]
I didn't create a pull request because it may or may not require manually installation in your part.

This is a sample dependabot config, you may edit it to your liking then save it to `.github/dependabot.yml`:

```yaml
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - dependabot
  - github-actions
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  - rust
```

**Notes:** The `labels` field are the pull request labels. They cannot be automatically created. You must create them in GitHub UI manually if you want to use them.
